server:
  port: 8084
spring:
  application:
    name: catalog-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: catalog_db
      username: admin
      password: password

  rabbitmq:
    addresses: localhost
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

springdoc:
  swagger-ui:
    enabled: true
    path: /catalog/swagger-ui.html

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG
            mapping: DEBUG
            repository: DEBUG