server:
  port: 8084
spring:
  application:
    name: catalog-service
  data:
    mongodb:
        host: localhost
        port: 27017
        database: catalog_db
        username: root
        password: example

  rabbitmq:
        addresses: localhost:5672
        username: guest
        password: guest

eureka:
  client:
    service-url:
      defaultZone: http://eureka.local:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

springdoc:
  swagger-ui:
    enabled: true
    path: /catalog/swagger-ui.html