server:
  port: 8082
spring:
  application:
        name: auth-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3386/db_user
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user_db_user
    password: password_user_db_user
eureka:
    client:
      service-url:
        defaultZone: http://eureka.local:8761/eureka/
    instance:
        prefer-ip-address: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
springdoc:
  swagger-ui:
    enabled: true
    path: /user/swagger-ui.html