version: "3.9"
services:

#  gateway:
#    image: ecommerce-apigetway:latest
#    container_name: "gateway"
#    ports:
#      - 8081:8081
#    networks:
#      - rabbitmq
#    depends_on:
#      - service-discovery
#      - mysqldb
#  authentication:
#    image: ecommerce-authentication:latest
#    container_name: "authentication"
#    networks:
#      - rabbitmq
#    depends_on:
#      - service-discovery
#      - mysqldb
#  cart :
#    image: ecommerce-cart:latest
#    container_name: "cart"
#    networks:
#      - rabbitmq
#
#  catalog:
#      image: ecommerce-catalog:latest
#      container_name: "catalog"
#      networks:
#          - rabbitmq
#      depends_on:
#        - service-discovery
#        - mongodb
#
#  order:
#    image: ecommerce-order:latest
#    container_name: "order"
#    networks:
#      - rabbitmq
#    depends_on:
#      - service-discovery
#      - mysqldb
#
#  payment:
#    image: ecommerce-payment:latest
#    container_name: "payment"
#    networks:
#      - rabbitmq
#    depends_on:
#      - service-discovery
#      - mysqldb
#
#  service-discovery:
#    image: ecommerce-servicediscovery:latest
#    container_name: "service-discovery"
#    ports:
#      - 8761:8761
#    networks:
#      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq
    restart: unless-stopped

  mysqldb:
    image: mysql
    container_name: "mysqldb"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    command:
      - --init-file
      - /docker-entrypoint-initdb.d/init.sql
    ports:
      - "3386:3306"
    volumes:
      - ~/.docker-conf/mysql/data/:/var/lib/mysql
      - ~/.docker-conf/mysql/conf/:/etc/mysql/conf.d
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rabbitmq
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "phpmyadmin"
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8008:80"
    networks:
      - rabbitmq
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: catalog_db
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ~/.docker-conf/mongodb/data:/data/db
    ports:
      - "27017:27017"
    networks:
        - rabbitmq


networks:
    rabbitmq:
        driver: bridge