version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq
    restart: unless-stopped

  mysqldb:
    image: mysql
    container_name: "mysqldb"
    environment:
      MYSQL_ROOT_PASSWORD: root
    command:
      - --init-file
      - /docker-entrypoint-initdb.d/init.sql
    ports:
      - 3386:3306
    volumes:
      - ~/.docker-conf/mysql/data/:/var/lib/mysql
      - ~/.docker-conf/mysql/conf/:/etc/mysql/conf.d
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rabbitmq
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "phpmyadmin"
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 8008:80
    networks:
      - rabbitmq
    restart: unless-stopped

  mongodb:
    image: mongo
    container_name: "mongodb"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: catalog_db
    ports:
      - 27017:27017
    networks:
        - rabbitmq
    volumes:
      - ~/.docker-conf/mongodb/data:/data/db

  mongo-express:
      image: mongo-express
      container_name: "mongo-express"
      restart: always
      ports:
        - 8009:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example
        ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
        ME_CONFIG_BASICAUTH: false
      networks:
        - rabbitmq
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_DB=postgres
      - KEYCLOAK_DB_VENDOR=postgres
      - KEYCLOAK_DB_URL=jdbc:postgresql://localhost:5436/keycloak
      - KEYCLOAK_DB_USERNAME=keycloak
      - KEYCLOAK_DB_PASSWORD=password
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=adminpassword
      - KEYCLOAK_LOGLEVEL=INFO
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command:
      - start-dev
    networks:
      - rabbitmq

  postgres:
      image: postgres:13
      environment:
        - POSTGRES_DB=keycloak
        - POSTGRES_USER=keycloak
        - POSTGRES_PASSWORD=password
      ports:
        - "5436:5432"
      volumes:
        - postgres-data:/var/lib/postgresql/data
      networks:
        - rabbitmq

volumes:
    postgres-data:

networks:
    rabbitmq:
        driver: bridge