server:
  port: 8081

spring:
  application:
        name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - PrefixPath=/api
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
          filters:
            - PrefixPath=/api
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
          filters:
            - PrefixPath=/api

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**
          filters:
            - PrefixPath=/api

        - id: order-service
          uri: lb://order-service
          predicates:
              - Path=/order/**
          filters:
              - PrefixPath=/api

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
          filters:
            - PrefixPath=/api


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
logging:
    level:
        org.springframework.cloud.gateway: DEBUG