server:
  port: 8081

spring:
  application:
        name: GATEWAY-SERVICE
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-service-swagger
          uri: lb://auth-service # Use the service name as registered in Eureka
          predicates:
            - Path=/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
#logging:
#    level:
#        org.springframework.cloud.gateway: DEBUG