server:
  port: 8081

spring:
  application:
        name: gateway-service
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/realms/ecomerce
#      client:
#        registration:
#          keycloak:
#            client-id: ecommerce
#            client-secret: Lg6uFtBnA4Hqg2MHt0HQ478gXVJbOIFp
#            authorization-grant-type: client_credentials
#            scope: openid
#            provider: keycloak
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8080/realms/ecomerce
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - PrefixPath=/api
            - AddRequestHeader=X-Powered-By, Spring Boot Gateway Service
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
          filters:
            - PrefixPath=/api
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
          filters:
            - PrefixPath=/api

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
logging:
    level:
        org.springframework.cloud.gateway: DEBUG
        org.springframework.security: DEBUG