spring:
  application:
        name: order-service
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
  jpa:
    hibernate:
        ddl-auto: update
    show-sql: true
  datasource:
        url: jdbc:mysql://localhost:3386/order_db
        username: order_user
        password: order_password
server:
    port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true