server:
  port: 8086
spring:
  application:
    name: inventory-service
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3386/db_inventory
    username: user_db_inventory
    password: password_user_db_inventory

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

springdoc:
  swagger-ui:
    enabled: true
    path: /inventory/swagger-ui.html