spring:
  application:
    name: EurekaService1

server:
  port: 8761
eureka:
  instance:
    hostname: eurekaserver1
    appname: EurekaCluster
  environment: local
  client:
#    serviceUrl:
#      defaultZone: http://eurekaserver1:8762/eureka/
#    register-with-eureka: true
#    fetch-registry: true
    register-with-eureka: false
    fetch-registry: false
