spring:
  application:
        name: payment-service
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
  jpa:
    hibernate:
        ddl-auto: update
    show-sql: true
  datasource:
        url: jdbc:mysql://localhost:3386/db_payment
        username: user_db_payment
        password: password_user_db_payment
server:
    port: 8088

springdoc:
  swagger-ui:
    enabled: true
    path: /payment/swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: http://eureka.local:8761/eureka/
    register-with-eureka: true
    fetch-registry: true