spring:
  application:
        name: cart-service
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
  jpa:
    hibernate:
        ddl-auto: update
    show-sql: true
  datasource:
        url: jdbc:mysql://localhost:3386/db_cart
        username: user_db_cart
        password: password_user_db_cart
server:
    port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://eureka.local:8761/eureka/
    register-with-eureka: true
    fetch-registry: true